# Build Module Workflow Configuration
name: create-module
description: "Interactive workflow to build complete BMAD modules with agents, workflows, tasks, and installation infrastructure"
author: "BMad"

# Critical variables load from config_source
config_source: "{bmad_folder}/bmb/config.yaml"
custom_module_location: "{config_source}:custom_module_location"
communication_language: "{config_source}:communication_language"
user_name: "{config_source}:user_name"

# Reference guides for module building
module_structure_guide: "{installed_path}/module-structure.md"
installer_templates: "{installed_path}/installer-templates/"

# Use existing build workflows
agent_builder: "{bmad_folder}/bmb/workflows/create-agent/workflow.yaml"
workflow_builder: "{bmad_folder}/bmb/workflows/create-workflow/workflow.yaml"
brainstorming_workflow: "{bmad_folder}/core/workflows/brainstorming/workflow.yaml"
brainstorming_context: "{installed_path}/brainstorm-context.md"

# Optional docs that help understand module patterns
recommended_inputs:
  - module_brief: "{output_folder}/module-brief-*.md"
  - brainstorming_results: "{output_folder}/brainstorming-*.md"
  - bmm_module: "{bmad_folder}/bmm/"
  - cis_module: "{bmad_folder}/cis/"
  - existing_agents: "{bmad_folder}/*/agents/"
  - existing_workflows: "{bmad_folder}/*/workflows/"

# Module path and component files
installed_path: "{bmad_folder}/bmb/workflows/create-module"
template: false # This is an interactive scaffolding workflow
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Output configuration - creates entire module structure
# Save to custom_module_location/{{module_code}}
installer_output_folder: "{custom_module_location}/{{module_code}}"

standalone: true

# Web bundle configuration
web_bundle: false # BMB workflows run locally in BMAD-METHOD project
